receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "xxxxxxxxxxxxxxxxxxxxxxx"
      "x-honeycomb-dataset": "test-bug-224"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
      
