service: testbug224
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  stage: dev
  region: eu-west-3

functions:
  test-bug-224:
    handler: handler.test
    layers:
      - arn:aws:lambda:eu-west-3:901920570463:layer:aws-otel-nodejs-amd64-ver-1-7-0:1
    timeout: 2
    memorySize: 128
    events:
      - httpApi:
          path: /test
          method: get
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
      OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/otel-config.yaml
      OTEL_LOG_LEVEL:	all
      OTEL_PROPAGATORS:	tracecontext
      OTEL_SERVICE_NAME: test-bug-224
      OTEL_TRACES_SAMPLER:	always_on
